baseurl = "http://127.0.0.1:1313/"
title = "lee Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
disqusShortname = "lee"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg.jpg"
  SEOTitle = "李宗蔚的博客 | lee Blog"
  description = "李宗蔚，程序员, 开源爱好者，生活探险家 | 这里是 李宗蔚 的博客，与你一起发现更大的世界。"
  keyword = "李宗蔚, lee, lee, , 李宗蔚的网络日志, 李宗蔚的博客, lee Blog, 博客, 个人网站, 互联网, Web, 云原生, PaaS, Docker, Kubernetes, 微服务, spring"
  slogan = "u got walk on your foot"

  image_404 = "img/404-bg.jpg"
  title_404 = "long long ago，there are no things :("

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false 
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "img/03.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  facebook      = "https://facebook.com/"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://mobile.twitter.com/"
  #linkedin       = "full profile url in linkedin"
  stackoverflow  = "https://stackoverflow.com/"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/MiKane200/leemjournals"
  wechat         = "https://web.wechat.com/"
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  title = "Lee的博客"
  href =  "http://192.168.99.100:1313/"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesh中文网"
  href =  "http://www.servicemesh.cn"
  [[params.bookmark_link]]
  title = "Awesome Service Mesh"
  href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  [[params.bookmark_link]]
  title =  "Image Compression"
  href = "https://tinypng.com"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
